# -*- coding: utf-8 -*-
"""LAP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WATLKm6meWD8PkgFRgNJLNqcTI3tN8wB
"""

import numpy as np
import pandas as pd
import seaborn as sns
import joblib

dataset=pd.read_csv('train_u6lujuX_CVtuZ9i (1).csv')

dataset.head()

dataset.shape

dataset.isna().sum()

dataset=dataset.dropna() #dataset.dropna(inplace=True)

dataset.isna().sum()

dataset.head()

dataset

dataset.reset_index(inplace=True)

dataset

dataset['Dependents'].unique()

dataset['Dependents'].value_counts()

dataset['Dependents']=dataset['Dependents'].replace(to_replace='3+',value=4)

dataset['Dependents'].value_counts()

sns.countplot(dataset, x='Education', order=['Graduate', 'Not Graduate'])

sns.countplot(x='Education',hue='Loan_Status',data=dataset)

sns.countplot(x='Married',hue='Loan_Status',data=dataset)

dataset['Married'].unique()

dataset.head()

dataset.replace({'Married':{'Yes':1,'No':0},'Gender':{'Male':1,'Female':0},'Education':{'Graduate':1,'Not Graduate':0},'Self_Employed':{'Yes':1,'No':0},'Property_Area':{'Rural':0,'Urban':1,'Semiurban':2}},inplace=True)

dataset.head()

dataset['Dependents']=dataset['Dependents'].astype('int')

x=dataset.iloc[:,2:-1].values

x[0]

dataset.replace({'Loan_Status':{'Y':1,'N':0}},inplace=True)

y=dataset.iloc[:,-1].values

y

x

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

x_train.shape

x_test.shape

from sklearn.ensemble import RandomForestClassifier
clas= RandomForestClassifier(n_estimators=28,criterion='entropy')
clas.fit(x_train,y_train)

y_pred=clas.predict(x_test)

from sklearn.metrics import confusion_matrix
sns.heatmap(confusion_matrix(y_test,y_pred),annot=True)

from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)

joblib.dump(clas, 'loan_model.joblib')